### PR TITLE
Support more GHC versions

### PR DESCRIPTION
**Pull request by gwils**

### CODE REVIEW

**Comment by gwils** [comment]
As a hackage trustee, I've revised these-skinny 0.7.4, since it was giving bad install plans on GHC 8.0, 7.10, and 7.8

**Comment by chessai** [comment]
Ah, must've been lazy when testing the truthfulness of my build claims. Sorry about that.

**Comment by gwils** [comment]
Would you be interested in a Travis CI suite generated by the haskell-ci script? It takes very little effort and builds each commit against each GHC version you claim to support.
I find this very valuable on pull requests, in case, for example, I forgot to import <$> from Control. Applicative on some old GHC version

**Comment by chessai** [comment]
That would be useful. How do i get set up with that?

**Comment by gwils** [comment]
Clone [this](https://github.com/haskell-CI/haskell-ci), then cabal new-install install it and run it following the instructions in the README. `these-skinny`'s cabal file already has the necessary `tested-with` metadata.
You also need to visit travis-ci.org and enable it for this repo.

**Pull request merged**
